# Generated by Django 3.2.16 on 2024-06-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsfollow',
            name='Follow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.follow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postsfollow',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
    ]
