# Generated by Django 3.2.16 on 2024-06-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20240628_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostsFollow',
        ),
    ]
