# Generated by Django 3.2.16 on 2024-06-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20240629_1454'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='Unique person constraint',
        ),
    ]
