# Generated by Django 3.2.16 on 2024-06-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_follow_unique person constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
    ]
