# Generated by Django 3.2.16 on 2024-06-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
