# Generated by Django 3.2.16 on 2024-06-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pub_date',)},
        ),
    ]
